In [2]:
import pandas as pd

In [3]:
cville = pd.read_csv('cville2.csv')
dulles = pd.read_csv('dulles2.csv')
norfolk = pd.read_csv('norfolk2.csv')
lynchburg = pd.read_csv('lynchburg2.csv')
dom = pd.read_csv('DOM_hourly.csv')

In [20]:
weatherdf = pd.concat([cville, dulles, norfolk, lynchburg], ignore_index=True)
weatherdf.drop(columns=['Entry_ID', 'REPORT_TYPE', 'SOURCE'], inplace=True)
weatherdf.head()

,STATION,DATE,DailyAverageDewPointTemperature,DailyAverageDryBulbTemperature,DailyAverageRelativeHumidity,DailyAverageSeaLevelPressure,DailyAverageStationPressure,DailyAverageWetBulbTemperature,DailyAverageWindSpeed,DailyCoolingDegreeDays,...,ShortDurationPrecipitationValue030,ShortDurationPrecipitationValue045,ShortDurationPrecipitationValue060,ShortDurationPrecipitationValue080,ShortDurationPrecipitationValue100,ShortDurationPrecipitationValue120,ShortDurationPrecipitationValue150,ShortDurationPrecipitationValue180,Sunrise,Sunset
0,Charlottesville,2005-12-31 23:00:00,NaN,45.0,NaN,NaN,29.10,NaN,4.2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,730.0,1704.0
1,Charlottesville,2006-01-01 23:00:00,NaN,42.0,NaN,NaN,29.36,NaN,1.8,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,730.0,1705.0
2,Charlottesville,2006-01-02 23:00:00,NaN,35.0,NaN,NaN,29.28,NaN,1.2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,731.0,1705.0
3,Charlottesville,2006-01-03 23:00:00,NaN,44.0,NaN,NaN,29.11,NaN,1.7,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,731.0,1706.0
4,Charlottesville,2006-01-04 23:00:00,NaN,42.0,NaN,NaN,29.25,NaN,3.9,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,731.0,1707.0

In [21]:
weatherdf['DATE'] = pd.to_datetime(weatherdf['DATE'])
dom['Datetime'] = pd.to_datetime(dom['Datetime'])
# round to the hour to prevent errors
weatherdf['DATE'] = weatherdf['DATE'].dt.floor('H')
dom['Datetime'] = dom['Datetime'].dt.floor('H')

# merge weather and energy dfs 
df = pd.merge(weatherdf, dom, left_on='DATE', right_on='Datetime', how='inner')
df

,STATION,DATE,DailyAverageDewPointTemperature,DailyAverageDryBulbTemperature,DailyAverageRelativeHumidity,DailyAverageSeaLevelPressure,DailyAverageStationPressure,DailyAverageWetBulbTemperature,DailyAverageWindSpeed,DailyCoolingDegreeDays,...,ShortDurationPrecipitationValue060,ShortDurationPrecipitationValue080,ShortDurationPrecipitationValue100,ShortDurationPrecipitationValue120,ShortDurationPrecipitationValue150,ShortDurationPrecipitationValue180,Sunrise,Sunset,Datetime,DOM_MW
0,Charlottesville,2005-12-31 23:00:00,NaN,45.0,NaN,NaN,29.10,NaN,4.2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,730.0,1704.0,2005-12-31 23:00:00,9991.0
1,Dulles,2005-12-31 23:00:00,NaN,40.0,NaN,NaN,29.46,NaN,2.2,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,728.0,1657.0,2005-12-31 23:00:00,9991.0
2,Norfolk,2005-12-31 23:00:00,NaN,45.0,NaN,NaN,29.80,NaN,7.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,718.0,1658.0,2005-12-31 23:00:00,9991.0
3,Lynchburg,2005-12-31 23:00:00,NaN,45.0,NaN,NaN,28.81,NaN,4.7,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,731.0,1709.0,2005-12-31 23:00:00,9991.0
4,Charlottesville,2006-01-01 23:00:00,NaN,42.0,NaN,NaN,29.36,NaN,1.8,0,...,NaN,NaN,NaN,NaN,NaN,NaN,730.0,1705.0,2006-01-01 23:00:00,10467.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18362,Norfolk,2016-11-12 23:00:00,32.0,45.0,63.0,30.31,30.25,40.0,11.4,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,641.0,1657.0,2016-11-12 23:00:00,10825.0
18363,Lynchburg,2016-11-12 23:00:00,26.0,41.0,60.0,30.34,29.29,35.0,2.7,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,654.0,1708.0,2016-11-12 23:00:00,10825.0
18364,Dulles,2017-10-29 23:00:00,54.0,55.0,96.0,29.49,29.20,54.0,11.5,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,634.0,1713.0,2017-10-29 23:00:00,8868.0
18365,Norfolk,2017-10-29 23:00:00,61.0,59.0,92.0,29.49,29.47,62.0,7.1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,625.0,1711.0,2017-10-29 23:00:00,8868.0
18366,Lynchburg,2017-10-29 23:00:00,48.0,51.0,84.0,29.49,28.53,50.0,6.2,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,638.0,1722.0,2017-10-29 23:00:00,8868.0

In [50]:
cols_keep = ['STATION', 'DATE', 'Sunrise', 'Sunset', 'DOM_MW']

cols_keep2 = cols_keep + [col for col in df.columns if 'daily' in col.lower()] 

df2 = df[cols_keep2].copy() 

cols_fixing = ['DailyAverageDewPointTemperature', 'DailyAverageDryBulbTemperature',
       'DailyAverageRelativeHumidity', 'DailyAverageSeaLevelPressure',
       'DailyAverageStationPressure', 'DailyAverageWetBulbTemperature',
       'DailyAverageWindSpeed', 'DailyCoolingDegreeDays',
       'DailyDepartureFromNormalAverageTemperature', 'DailyHeatingDegreeDays',
       'DailyMaximumDryBulbTemperature', 'DailyMinimumDryBulbTemperature',
       'DailyPeakWindDirection', 'DailySustainedWindDirection', 'DailySustainedWindSpeed', 
       'DailyPeakWindSpeed', 'DailyPrecipitation', 'DailySnowfall', 'DailySnowDepth' ]

df2['DailyPrecipitation'] = df2['DailyPrecipitation'].astype(str).str.strip().replace('T', 0)
df2['DailySnowfall'] = df2['DailySnowfall'].astype(str).str.strip().replace('T', 0)
df2['DailySnowDepth'] = df2['DailySnowDepth'].astype(str).str.strip().replace('T', 0)

for col in cols_fixing:
    # Option 1: remove unwanted characters (like 's') and convert to float
    df2[col] = df2[col].fillna(0)
    df2[col] = df2[col].astype(str).str.replace('s', '', regex=False)
    df2[col] = df2[col].astype(str).str.replace('s ', '', regex=False)

    try:
        df2[col] = df2[col].astype(float)
        # print(col)
    except Exception as e:
        # If it fails, fall back to pd.to_numeric with coercion
        df2[col] = pd.to_numeric(df2[col], errors='coerce')
        # print(f"Column '{col}' had conversion issues, used pd.to_numeric as fallback.")

df2['DATE'] = pd.to_datetime(df2['DATE'], format='%Y-%m-%d') 
df2['Month'] = df2['DATE'].dt.month
df2['DayOfWeek'] = df2['DATE'].dt.dayofweek  # 0=Monday
df2['DayOfYear'] = df2['DATE'].dt.dayofyear

df2.columns

Index(['STATION', 'DATE', 'Sunrise', 'Sunset', 'DOM_MW',
       'DailyAverageDewPointTemperature', 'DailyAverageDryBulbTemperature',
       'DailyAverageRelativeHumidity', 'DailyAverageSeaLevelPressure',
       'DailyAverageStationPressure', 'DailyAverageWetBulbTemperature',
       'DailyAverageWindSpeed', 'DailyCoolingDegreeDays',
       'DailyDepartureFromNormalAverageTemperature', 'DailyHeatingDegreeDays',
       'DailyMaximumDryBulbTemperature', 'DailyMinimumDryBulbTemperature',
       'DailyPeakWindDirection', 'DailyPeakWindSpeed', 'DailyPrecipitation',
       'DailySnowDepth', 'DailySnowfall', 'DailySustainedWindDirection',
       'DailySustainedWindSpeed', 'DailyWeather', 'Month', 'DayOfWeek',
       'DayOfYear'],
      dtype='object')

In [51]:
# Classify extreme weather events (EWE) based on previous research done 

# make list of extreme weather codes to check for in the DailyWeather column 
extreme_codes = ['PL', 'DU', 'HZ', 'BLSN', 'FC', 'WIND', 'SN']

# iterate through each row and check for extreme weather conditions
for index, row in df2.iterrows():
    # convert to string to check for codes 
    weather = str(row['DailyWeather'])  
    if any(code in weather for code in extreme_codes):
        df2.at[index, 'EWE'] = 1

    # too high or too low pressure 
    elif row['DailyAverageStationPressure'] > 30.40 or row['DailyAverageStationPressure'] < 29.40:
        df2.at[index, 'EWE'] = 1

    # higher than 95 is extreme temp 
    elif row['DailyMaximumDryBulbTemperature'] > 95:
        df2.at[index, 'EWE'] = 1

    # lower than 10 is extreme temp
    elif row['DailyMinimumDryBulbTemperature'] < 10:
        df2.at[index, 'EWE'] = 1

    # daily precipitation greater than 2 inches is extreme
    elif row['DailyPrecipitation'] > 2:
        df2.at[index, 'EWE'] = 1
    
    # more than 2 inches of snow daily is extreme
    elif row['DailySnowfall'] > 2: 
        df2.at[index, 'EWE'] = 1
    
    # sustained wind speed greater than 58 mph is extreme
    elif row['DailySustainedWindSpeed'] > 58:
        df2.at[index, 'EWE'] = 1

    # else no extreme weather event
    else:
        df2.at[index, 'EWE'] = 0

df2['EWE'].value_counts()

0.0    9198
1.0    9169
Name: EWE, dtype: int64

In [52]:
# save final to csv 
df2.to_csv('final_df.csv', index=False)