In [ ]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
# load data 
dom = pd.read_csv('DOM_hourly.csv')
c59 = pd.read_csv('cville59.csv')
c918 = pd.read_csv('cville918.csv')
d59 = pd.read_csv('dulles59.csv')
d918 = pd.read_csv('dulles918.csv')
nor59 = pd.read_csv('nor59.csv')
nor918 = pd.read_csv('nor918.csv')
ly59 = pd.read_csv('ly59.csv')
ly918 = pd.read_csv('ly918.csv')

C:\Users\ilian\AppData\Local\Temp\ipykernel_12440\2807698824.py:3: DtypeWarning: Columns (3,31,37,38,42,43,49,50,52,54,56,57,61,64,96,111,112,115,118,120) have mixed types. Specify dtype option on import or set low_memory=False.
  c59 = pd.read_csv('cville59.csv')
C:\Users\ilian\AppData\Local\Temp\ipykernel_12440\2807698824.py:4: DtypeWarning: Columns (3,21,27,28,29,30,31,37,38,42,43,49,50,52,54,56,57,59,60,61,62,63,64,96,111,113,115,118,120) have mixed types. Specify dtype option on import or set low_memory=False.
  c918 = pd.read_csv('cville918.csv')
C:\Users\ilian\AppData\Local\Temp\ipykernel_12440\2807698824.py:5: DtypeWarning: Columns (35,36,42,43,44,50,52,72,76,77,90,97,98,99,100,101,102,103,104,105,106,107,108) have mixed types. Specify dtype option on import or set low_memory=False.
  d59 = pd.read_csv('dulles59.csv')
C:\Users\ilian\AppData\Local\Temp\ipykernel_12440\2807698824.py:6: DtypeWarning: Columns (35,36,42,43,44,47,50,52,74,76,90) have mixed types. Specify dtype option on import or set low_memory=False.
  d918 = pd.read_csv('dulles918.csv')
C:\Users\ilian\AppData\Local\Temp\ipykernel_12440\2807698824.py:7: DtypeWarning: Columns (36,42,43,44,47,50,52,59,60,70,76,77,89,90) have mixed types. Specify dtype option on import or set low_memory=False.
  nor59 = pd.read_csv('nor59.csv')
C:\Users\ilian\AppData\Local\Temp\ipykernel_12440\2807698824.py:8: DtypeWarning: Columns (36,42,43,44,47,50,52,53,57,76,77,90) have mixed types. Specify dtype option on import or set low_memory=False.
  nor918 = pd.read_csv('nor918.csv')
C:\Users\ilian\AppData\Local\Temp\ipykernel_12440\2807698824.py:9: DtypeWarning: Columns (35,36,42,43,44,47,50,76,90) have mixed types. Specify dtype option on import or set low_memory=False.
  ly59 = pd.read_csv('ly59.csv')
C:\Users\ilian\AppData\Local\Temp\ipykernel_12440\2807698824.py:10: DtypeWarning: Columns (35,36,42,43,44,47,50,52,74,76,90) have mixed types. Specify dtype option on import or set low_memory=False.
  ly918 = pd.read_csv('ly918.csv')

In [3]:
# drop columns don't need 
c59 = c59.drop(columns=['BackupDirection', 'BackupDistance', 'BackupDistanceUnit', 'BackupElements', 'BackupElevation', 'BackupElevationUnit', 'BackupEquipment', 'BackupLatitude', 'BackupLongitude', 'BackupName',
                        'AWND', 'CDSD', 'CLDD', 'DSNW', 'DYHF', 'DYTS', 'HDSD', 'HTDD','WindEquipmentChangeDate'])

c918 = c918.drop(columns=['BackupDirection', 'BackupDistance', 'BackupDistanceUnit', 'BackupElements', 'BackupElevation', 'BackupElevationUnit', 'BackupEquipment', 'BackupLatitude', 'BackupLongitude', 'BackupName',
                        'AWND', 'CDSD', 'CLDD', 'DSNW', 'DYHF', 'DYTS', 'HDSD', 'HTDD','WindEquipmentChangeDate'])

d59 = d59.drop(columns=['BackupDirection', 'BackupDistance', 'BackupDistanceUnit', 'BackupElements', 'BackupElevation', 'BackupElevationUnit', 'BackupEquipment', 'BackupLatitude', 'BackupLongitude', 'BackupName',
                        'AWND', 'CDSD', 'CLDD', 'DSNW', 'DYHF', 'DYTS', 'HDSD', 'HTDD','WindEquipmentChangeDate'])
d918 = d918.drop(columns=['BackupDirection', 'BackupDistance', 'BackupDistanceUnit', 'BackupElements', 'BackupElevation', 'BackupElevationUnit', 'BackupEquipment', 'BackupLatitude', 'BackupLongitude', 'BackupName',
                        'AWND', 'CDSD', 'CLDD', 'DSNW', 'DYHF', 'DYTS', 'HDSD', 'HTDD','WindEquipmentChangeDate'])

nor59 = nor59.drop(columns=['BackupDirection', 'BackupDistance', 'BackupDistanceUnit', 'BackupElements', 'BackupElevation', 'BackupElevationUnit', 'BackupEquipment', 'BackupLatitude', 'BackupLongitude', 'BackupName',
                        'AWND', 'CDSD', 'CLDD', 'DSNW', 'DYHF', 'DYTS', 'HDSD', 'HTDD','WindEquipmentChangeDate'])
nor918 = nor918.drop(columns=['BackupDirection', 'BackupDistance', 'BackupDistanceUnit', 'BackupElements', 'BackupElevation', 'BackupElevationUnit', 'BackupEquipment', 'BackupLatitude', 'BackupLongitude', 'BackupName',
                        'AWND', 'CDSD', 'CLDD', 'DSNW', 'DYHF', 'DYTS', 'HDSD', 'HTDD','WindEquipmentChangeDate'])

ly59 = ly59.drop(columns=['BackupDirection', 'BackupDistance', 'BackupDistanceUnit', 'BackupElements', 'BackupElevation', 'BackupElevationUnit', 'BackupEquipment', 'BackupLatitude', 'BackupLongitude', 'BackupName',
                        'AWND', 'CDSD', 'CLDD', 'DSNW', 'DYHF', 'DYTS', 'HDSD', 'HTDD','WindEquipmentChangeDate'])
ly918 = ly918.drop(columns=['BackupDirection', 'BackupDistance', 'BackupDistanceUnit', 'BackupElements', 'BackupElevation', 'BackupElevationUnit', 'BackupEquipment', 'BackupLatitude', 'BackupLongitude', 'BackupName',
                        'AWND', 'CDSD', 'CLDD', 'DSNW', 'DYHF', 'DYTS', 'HDSD', 'HTDD','WindEquipmentChangeDate'])

In [4]:
# combine all weather dataframes
weatherdf = pd.concat([c59, c918, d59, d918, nor59, nor918, ly59, ly918], ignore_index=True)
# sort by date and reset index
weatherdf = weatherdf.sort_values(by='DATE').reset_index(drop=True)
weatherdf

,STATION,DATE,REPORT_TYPE,SOURCE,DailyAverageDewPointTemperature,DailyAverageDryBulbTemperature,DailyAverageRelativeHumidity,DailyAverageSeaLevelPressure,DailyAverageStationPressure,DailyAverageWetBulbTemperature,...,ShortDurationPrecipitationValue030,ShortDurationPrecipitationValue045,ShortDurationPrecipitationValue060,ShortDurationPrecipitationValue080,ShortDurationPrecipitationValue100,ShortDurationPrecipitationValue120,ShortDurationPrecipitationValue150,ShortDurationPrecipitationValue180,Sunrise,Sunset
0,72403093738,2005-12-31T00:51:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,72308013737,2005-12-31T00:51:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,72401693736,2005-12-31T00:53:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,72410013733,2005-12-31T00:54:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,72403093738,2005-12-31T01:00:00,FM-12,4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671832,72308013737,2018-12-31T23:59:00,SOM,6,NaN,NaN,NaN,NaN,NaN,NaN,...,0.42,0.47,0.54,0.59,0.60,0.6,0.61,0.61,NaN,NaN
671833,72308013737,2018-12-31T23:59:00,SOD,6,53.0,56.0,93.0,30.16,30.16,54.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,718.0,1658.0
671834,72403093738,2018-12-31T23:59:00,SOD,6,40.0,39.0,99.0,30.13,29.82,41.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,728.0,1657.0
671835,72401693736,2018-12-31T23:59:00,SOD,6,NaN,44.0,NaN,NaN,29.45,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,730.0,1704.0
671836,72410013733,2018-12-31T23:59:00,SOM,6,NaN,NaN,NaN,NaN,NaN,NaN,...,0.27,0.36,0.41,0.48,0.51,0.57,0.59,0.62,NaN,NaN

In [5]:
# ensue in proper datetime format
weatherdf['DATE'] = pd.to_datetime(weatherdf['DATE'])
dom['Datetime'] = pd.to_datetime(dom['Datetime'])
# round to the hour to prevent errors
weatherdf['DATE'] = weatherdf['DATE'].dt.floor('H')
dom['Datetime'] = dom['Datetime'].dt.floor('H')

# merge weather and energy dfs 
df = pd.merge(weatherdf, dom, left_on='DATE', right_on='Datetime', how='inner')
df

,STATION,DATE,REPORT_TYPE,SOURCE,DailyAverageDewPointTemperature,DailyAverageDryBulbTemperature,DailyAverageRelativeHumidity,DailyAverageSeaLevelPressure,DailyAverageStationPressure,DailyAverageWetBulbTemperature,...,ShortDurationPrecipitationValue060,ShortDurationPrecipitationValue080,ShortDurationPrecipitationValue100,ShortDurationPrecipitationValue120,ShortDurationPrecipitationValue150,ShortDurationPrecipitationValue180,Sunrise,Sunset,Datetime,DOM_MW
0,72403093738,2005-12-31 00:00:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005-12-31 00:00:00,9945.0
1,72308013737,2005-12-31 00:00:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005-12-31 00:00:00,9945.0
2,72401693736,2005-12-31 00:00:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005-12-31 00:00:00,9945.0
3,72410013733,2005-12-31 00:00:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005-12-31 00:00:00,9945.0
4,72403093738,2005-12-31 01:00:00,FM-12,4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005-12-31 01:00:00,9389.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648595,72308013737,2018-08-03 00:00:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-08-03 00:00:00,11385.0
648596,72410013733,2018-08-03 00:00:00,FM-16,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-08-03 00:00:00,11385.0
648597,72403093738,2018-08-03 00:00:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-08-03 00:00:00,11385.0
648598,72401693736,2018-08-03 00:00:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-08-03 00:00:00,11385.0
648599,72410013733,2018-08-03 00:00:00,FM-15,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-08-03 00:00:00,11385.0

In [7]:
df2 = df.dropna(subset=['DailyAverageDryBulbTemperature']).copy()

# removes 's' from values and ensuring all are floats 
df2['DailyAverageDryBulbTemperature'] = (df2['DailyAverageDryBulbTemperature']
    .astype(str).str.replace('s', '', regex=False).astype(float))

# change station numbers to station names 
df2['STATION'] = df2['STATION'].replace({72403093738: 'Dulles', 72410013733: 'Lynchburg',72308013737: 'Norfolk',72401693736: 'Charlottesville'})
df2['STATION'].value_counts() 

# save to csv file 
df2.to_csv('final_df.csv', index=False)